### PR TITLE
aws-ses-email converted to lambda function

### PR DESCRIPTION
**Pull request by tolgaerdonmez**
aws-ses-email is too big for a lambda function, what should we do ?

### CODE REVIEW

**Comment by Proful** [comment]
There is a way to upload zip file. I don't think it is too big. It is misleading error message.

**Comment by tolgaerdonmez** [comment]
> There is a way to upload zip file. I don't think it is too big. It is misleading error message.

Yeah, I uploaded the zip file. But Shouldn't be a lambda function a single function javascript file. aws-ses-email module has many specialties, like rendering special email templates or so.

**Comment by Proful** [comment]
If you are still experiencing this problem we can have a call sometime.

**Comment by tolgaerdonmez** [comment]
> If you are still experiencing this problem we can have a call sometime. 

It is now not needed, thanks.

**Comment by johnjacobkenny** [comment]
Leaving this to @proful to merge

**Pull request merged**
